### PR TITLE
added some comments

### LINKED ISSUE #1: fibonacci.py rewrite and add comments
rewrite the file and add comments to the code

### PR DESCRIPTION
**Pull request by najeebib**

### CODE REVIEW

**Review by yosefkhayat — APPROVED** [review]
this looks fine :)

**Comment by Shqier** [comment]
Approved

**Review by yosefkhayat — CHANGES_REQUESTED** [review]
add more comments

**Comment by najeebib** [comment]
I have done it

**Review by yosefkhayat — APPROVED** [review]
good job

**Pull request merged**
